### ISSUE TITLE
Add pulp logo to README

### ISSUE THREAD

**Issue by mog13** [mog13/pulp#11]
There should be a logo below the PULP header.

use this logo:
![image](https://user-images.githubusercontent.com/6411677/47264417-ba7fdb80-d50e-11e8-997d-505d717070dd.png)

you will need markdown to do this, to find out how see here: https://guides.github.com/features/mastering-markdown/

**Comment by oyavri** [comment]
I think I can do this!

**Comment by mog13** [comment]
awesome, feel free to give it a go! if you get stuck i'm happy to help!
