### ISSUE TITLE
Add libraries

### ISSUE THREAD

**Issue by mog13** [mog13/pulp#13]
We need to add more libraries. These libraries should be anything that adds richness to an app or game and no necessarily function. If you have an idea for an addition but are unsure then link it in this issue and i will reply whether it would be a good fit or not! (otherwise you may risk getting your pull request rejected)

use your best judgement for which category it may fit under, but if you think it doesn't fit any feel free to add a new category!

use the following template:

```
**[libraryname](url to library preferably github)**
overview of library/description
```

This is an ongoing issue so i will be accepting multiple and ongoing pullrequests for it.

**Comment by alvesjtiago** [comment]
Hi @mog13, thanks for creating this repo!
Just submitted a couple of libraries to make sure this is the type of libraries you're looking for. If it is I'll research and add a couple more to the list.
