### ISSUE TITLE
Title for contributing should be fixed

### ISSUE THREAD

**Issue by mog13** [mog13/pulp#28]
The title in contribututing.js is broken and renders as `#CONTRIBUTING.md`

it should instead be a header in markdown reading `Contributing` (hint #'s need spaces before the title).

here is a resource for markdown:
https://guides.github.com/features/mastering-markdown/

**Comment by prashi23** [comment]
Hi! Can I work on this issue?

**Comment by mog13** [comment]
yup sounds good, I look forward to a pull request :)
